[package]
name = "domeworking"
version = "0.1.0"
authors = ["Chayim Refael Friedman <chayimfr@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
dome_cloomnik = "0.1"
anyhow = "1.0"
once_cell = "1.6"

[lib]
crate-type = ["cdylib"]
